/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cuiqiang_ling_ai_cmakedemo_MainActivity */

#ifndef _Included_cuiqiang_ling_ai_cmakedemo_MainActivity
#define _Included_cuiqiang_ling_ai_cmakedemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cuiqiang_ling_ai_cmakedemo_MainActivity
 * Method:    getStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cuiqiang_ling_ai_cmakedemo_MainActivity_getStr
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
